#!/bin/sh

cd examples;
echo -e "\033[36;1mMaking tests...\033[0m"
for file in $(ls *.bdsh)
do
    echo $file;
    echo 'x' | ./moul.sh bdsh.sh $file 1>&- 2>&-
    if [ $? -ne 0 ]
    then
	echo -e "\033[31mTest $file failed. Commit aborted.\033[0m";
	rm -f toto;
	exit 1;
    fi
done

exit 0;
